# Generated by Django 3.0.5 on 2020-04-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20200430_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='www.ChoiceType'),
            preserve_default=False,
        ),
    ]
