# Generated by Django 3.0.5 on 2020-04-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_choice_choice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
