# Generated by Django 3.0.5 on 2020-05-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20200510_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='rickmaster2008', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
