# Generated by Django 3.0.5 on 2020-04-30 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20200430_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='www.ChoiceType'),
        ),
    ]
