# Generated by Django 3.0.5 on 2020-05-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_auto_20200501_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicetype',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_types', to='www.Product'),
        ),
    ]
