# Generated by Django 3.0.5 on 2020-05-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0010_auto_20200501_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
