# Generated by Django 3.0.5 on 2020-05-01 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0012_order_orderitem_orderitemchoices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItemChoices',
            new_name='OrderItemChoice',
        ),
    ]
